In [1]:
import pandas as pd

### Q1. Pandas version

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

```python
pd.__version__
```

In [2]:
pd.__version__

'2.3.2'

### Getting the data 

For this homework, we'll use the Car Fuel Efficiency dataset. Download it from <a href='https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'>here</a>.

You can do it with wget:
```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
```

Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [3]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count

How many records are in the dataset?

- 4704
- 8704
- 9704
- 17704

In [5]:
df.shape

(9704, 11)

### Q3. Fuel types

How many fuel types are presented in the dataset?

- 1
- 2
- 3
- 4

In [10]:
df.groupby("fuel_type").size()

fuel_type
Diesel      4806
Gasoline    4898
dtype: int64

### Q4. Missing values

How many columns in the dataset have missing values?

- 0
- 1
- 2
- 3
- 4

In [8]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

- 13.75
- 23.75
- 33.75
- 43.75

In [12]:
df[df["origin"]=="Asia"]["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

### Q6. Median value of horsepower



1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?


- Yes, it increased
- Yes, it decreased
- No

In [11]:
df['horsepower'].median()

np.float64(149.0)

In [12]:
df['horsepower'].mode()[0]

np.float64(152.0)

In [13]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])
df['horsepower'].median()

np.float64(152.0)

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.051
- 0.51
- 5.1
- 51

In [25]:
import numpy as np

In [20]:
# 1. Select all the cars from Asia
# 2. Select only columns `vehicle_weight` and `model_year`
# 3. Select the first 7 values
# 4. Get the underlying NumPy array. Let's call it `X`.
X = df[df["origin"]=="Asia"][["vehicle_weight", "model_year"]].head(7).to_numpy()

In [21]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [22]:
# 5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
XTX = X.T.dot(X)

In [23]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [26]:
# 7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [27]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [28]:
# 8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
w = np.linalg.inv(XTX).dot(X.T).dot(y)

In [29]:
w

array([0.01386421, 0.5049067 ])

In [30]:
# 9. What's the sum of all the elements of the result?
w.sum()

np.float64(0.5187709081074016)